#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ "${COMMIT_SOURCE}" = merge ];then
    exit 0
fi

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor): +#([0-9]+) - .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,150}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi
