- name: Install NodeJS
  become: yes
  become_flags: -i
  become_user: jose-da-silva-neto
  block:
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

    - name: Source nvm in ~/.{{ item }}
      lineinfile: >
          dest=~/.{{ item }}
          line="source ~/.nvm/nvm.sh"
          create=yes
      tags: nvm
      with_items:
        - bashrc
        - profile

    - name: Install node and set version
      become: yes
      become_user: jose-da-silva-neto
      shell: "source $HOME/.nvm/nvm.sh && nvm install {{node.version}} && nvm alias default {{node.version}}" 
      args:
        executable: /bin/bash