- name: Install Docker
  become: true
  block:
    - name: Install docker dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Adds GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get Binary Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Ensure Docker group is present
      group:
        name: docker
        state: present

    - name: Add current user to the Docker group
      user:
        name: "{{ docker.user }}"
        groups:
          - docker
        append: yes

    - name: Add current user docker.sock
      command: sudo chown {{ docker.user }}:docker /var/run/docker.sock

    - name: Ensure service is enabled
      command: service docker restart
